title: Juandi Guitar
author: juandiegov16
email: jdvallejo16@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my world.

# social links
twitter_username: @JuanDiegoV16
github_username:  juandiegov16
instagram_username: juandiegov16
reddit_username: GreenQuokka

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
